version: "3.8"
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A worker worker -l info
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - .:/app

  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - redis
      - worker
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - .:/app